In [1]:
from Agent import Agent
from Grid import Grid

# 3.1
De code achter alle functies is te vinden in de zelf geschreven Grid en Agent Class. 

In [2]:
grid_movement_demo = Grid(width=4, height=4, terminal=[(3, 0), (0, 3), (3, 1)], start=(3, 2), prob=1)
print(str(grid_movement_demo.grid))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [3]:
rewards = [
        [-1, -1, -1, 40],
        [-1, -1, -10, -10],
        [-1, -1, -1, -1],
        [10, -2, -1, -1]
]

In [4]:
grid_movement_demo.set(rewards)
print(str(grid_movement_demo.rewards))

[[ -1  -1  -1  40]
 [ -1  -1 -10 -10]
 [ -1  -1  -1  -1]
 [ 10  -2  -1  -1]]


De '1' in deze numpy array staat voor agent. 

In [11]:
agent = Agent(grid_movement_demo.start)
grid_movement_demo.set_agent(agent)
grid_movement_demo.demonstrate_movement(agent)

Moving right..
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 1]]
------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 1]]
------
Moving up..
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
------
[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 1 0 0]]
------
Moving left..
[[0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 1 0 0]]
------
[[0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]]
------
Moving down..
[[0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]
------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]]
------


In [12]:
grid_movement_demo2 = Grid(width=4, height=4, terminal=[(3, 0), (0, 3), (3, 1)], start=(3, 2))
agent2 = Agent(grid_movement_demo2.start)
grid_movement_demo2.set_agent(agent2)
grid_movement_demo2.demonstrate_movement(agent2)

Moving right..
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]
------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]
------
Moving up..
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]
------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]
------
Moving left..
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]
------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]]
------
Moving down..
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]]
------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]
------


# 3.2
Eerst wordt de utility van iedere state berekend.

In [13]:
grid = Grid(width=4, height=4, terminal=[[3, 0], [0, 3], [3, 1]], start=(3, 2), prob=1)
grid.set(rewards)

agent3 = Agent(grid.start)
grid.set_agent(agent3)

grid.value_iteration()

Iteration  0
----------------------------------------------
[[-1. -1. 40.  0.]
 [-1. -1. -1. 40.]
 [10. -1. -1. -1.]
 [ 0.  0. -1. -1.]]
[['>' '<' '>' 'X']
 ['>' '<' '<' '^']
 ['V' '<' '<' '<']
 ['X' 'X' '>' '<']]
40.0
Iteration  1
----------------------------------------------
[[-2. 39. 40.  0.]
 [ 9. 38. 39. 40.]
 [10. 37. 36. 35.]
 [ 0.  0. 35. 34.]]
[['>' '>' '>' 'X']
 ['V' '^' '^' '^']
 ['V' '^' '<' '<']
 ['X' 'X' '^' '<']]
40.0
Iteration  2
----------------------------------------------
[[38. 39. 40.  0.]
 [37. 38. 39. 40.]
 [36. 37. 36. 35.]
 [ 0.  0. 35. 34.]]
[['>' '>' '>' 'X']
 ['>' '^' '^' '^']
 ['>' '^' '<' '<']
 ['X' 'X' '^' '<']]
40.0
Iteration  3
----------------------------------------------
[[38. 39. 40.  0.]
 [37. 38. 39. 40.]
 [36. 37. 36. 35.]
 [ 0.  0. 35. 34.]]
[['>' '>' '>' 'X']
 ['>' '^' '^' '^']
 ['>' '^' '<' '<']
 ['X' 'X' '^' '<']]
0


array([[37., 38., 39., 40.],
       [36., 37., 29., 30.],
       [35., 36., 35., 34.],
       [10., -2., 34., 33.]])

Daarna pas probeert de agent het gegeven pad (policy) te volgen. 

In [14]:
grid.traverse_path(agent3)

[0 0 0 0] ['>' '>' '>' 'X']
[0 0 0 0] ['>' '^' '^' '^']
[0 0 1 0] ['>' '^' '<' '<']
[0 0 0 0] ['X' 'X' '^' '<']

 ---------------------
[0 0 0 0] ['>' '>' '>' 'X']
[0 0 0 0] ['>' '^' '^' '^']
[0 1 0 0] ['>' '^' '<' '<']
[0 0 0 0] ['X' 'X' '^' '<']

 ---------------------
[0 0 0 0] ['>' '>' '>' 'X']
[0 1 0 0] ['>' '^' '^' '^']
[0 0 0 0] ['>' '^' '<' '<']
[0 0 0 0] ['X' 'X' '^' '<']

 ---------------------
[0 1 0 0] ['>' '>' '>' 'X']
[0 0 0 0] ['>' '^' '^' '^']
[0 0 0 0] ['>' '^' '<' '<']
[0 0 0 0] ['X' 'X' '^' '<']

 ---------------------
[0 0 1 0] ['>' '>' '>' 'X']
[0 0 0 0] ['>' '^' '^' '^']
[0 0 0 0] ['>' '^' '<' '<']
[0 0 0 0] ['X' 'X' '^' '<']

 ---------------------
[0 0 0 1] ['>' '>' '>' 'X']
[0 0 0 0] ['>' '^' '^' '^']
[0 0 0 0] ['>' '^' '<' '<']
[0 0 0 0] ['X' 'X' '^' '<']

 ---------------------
