In [11]:
from Agent import Agent
from Grid import Grid

# 3.1
De code achter alle functies is te vinden in de zelf geschreven Grid en Agent Class. 

In [19]:
grid_movement_demo = Grid(width=4, height=4, terminal=[(3, 0), (0, 3), (3, 1)], start=(3, 2), prob=1)
print(str(grid.grid))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]]


In [20]:
rewards = [
        [-1, -1, -1, 40],
        [-1, -1, -10, -10],
        [-1, -1, -1, -1],
        [10, -2, -1, -1]
]

In [21]:
grid_movement_demo.set(rewards)
print(str(grid.rewards))

[[ -1  -1  -1  40]
 [ -1  -1 -10 -10]
 [ -1  -1  -1  -1]
 [ 10  -2  -1  -1]]


De '1' in deze numpy array staat voor agent. 

In [22]:
agent = Agent(grid.start)
grid_movement_demo.set_agent(agent)
grid_movement_demo.demonstrate_movement(agent)

Moving right..
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]
------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]
------
Moving up..
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]
------
[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]
------
Moving left..
[[0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]]
------
[[0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]]
------
Moving down..
[[0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]]
------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]]
------


In [23]:
grid_movement_demo2 = Grid(width=4, height=4, terminal=[(3, 0), (0, 3), (3, 1)], start=(3, 2))
agent2 = Agent(grid_movement_demo2.start)
grid_movement_demo2.set_agent(agent2)
grid_movement_demo2.demonstrate_movement(agent2)

Moving right..
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]
------
Moving  <  instead
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]
------
Moving up..
[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]]
------
Moving  >  instead
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]
------
Moving left..
[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]]
------
Moving  >  instead
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]
------
Moving down..
Moving  >  instead
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]
------
Moving  <  instead
[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]]
------


# 3.2
Eerst wordt de utility van iedere state berekend.

In [27]:
grid = Grid(width=4, height=4, terminal=[[3, 0], [0, 3], [3, 1]], start=(3, 2), prob=1)
grid.set(rewards)

agent3 = Agent(grid.start)
grid.set_agent(agent3)

grid.value_iteration()

Iteration  0
----------------------------------------------
[[-2 -2 80  0]
 [-2 -2 -2 80]
 [20 -2 -2 -2]
 [ 0  0 -2 -2]]
[['>' '<' '>' 'X']
 ['>' '<' '<' '^']
 ['V' '<' '<' '<']
 ['X' 'X' '>' '<']]
80
Iteration  1
----------------------------------------------
[[-4 78 80  0]
 [18 76 78 80]
 [20 74 72 70]
 [ 0  0 70 68]]
[['>' '>' '>' 'X']
 ['V' '^' '^' '^']
 ['V' '^' '<' '<']
 ['X' 'X' '^' '<']]
80
Iteration  2
----------------------------------------------
[[76 78 80  0]
 [74 76 78 80]
 [72 74 72 70]
 [ 0  0 70 68]]
[['>' '>' '>' 'X']
 ['>' '^' '^' '^']
 ['>' '^' '<' '<']
 ['X' 'X' '^' '<']]
80
Iteration  3
----------------------------------------------
[[76 78 80  0]
 [74 76 78 80]
 [72 74 72 70]
 [ 0  0 70 68]]
[['>' '>' '>' 'X']
 ['>' '^' '^' '^']
 ['>' '^' '<' '<']
 ['X' 'X' '^' '<']]
0


array([[75, 77, 79, 40],
       [73, 75, 68, 70],
       [71, 73, 71, 69],
       [10, -2, 69, 67]])

Daarna pas probeert de agent het gegeven pad (policy) te volgen. 

In [28]:
grid.traverse_path(agent3)

[0 0 0 0] ['>' '>' '>' 'X']
[0 0 0 0] ['>' '^' '^' '^']
[0 0 0 0] ['>' '^' '<' '<']
[0 0 1 0] ['X' 'X' '^' '<']

 ---------------------
[0 0 0 0] ['>' '>' '>' 'X']
[0 0 0 0] ['>' '^' '^' '^']
[0 0 1 0] ['>' '^' '<' '<']
[0 0 0 0] ['X' 'X' '^' '<']

 ---------------------
[0 0 0 0] ['>' '>' '>' 'X']
[0 0 0 0] ['>' '^' '^' '^']
[0 1 0 0] ['>' '^' '<' '<']
[0 0 0 0] ['X' 'X' '^' '<']

 ---------------------
[0 0 0 0] ['>' '>' '>' 'X']
[0 1 0 0] ['>' '^' '^' '^']
[0 0 0 0] ['>' '^' '<' '<']
[0 0 0 0] ['X' 'X' '^' '<']

 ---------------------
[0 1 0 0] ['>' '>' '>' 'X']
[0 0 0 0] ['>' '^' '^' '^']
[0 0 0 0] ['>' '^' '<' '<']
[0 0 0 0] ['X' 'X' '^' '<']

 ---------------------
[0 0 1 0] ['>' '>' '>' 'X']
[0 0 0 0] ['>' '^' '^' '^']
[0 0 0 0] ['>' '^' '<' '<']
[0 0 0 0] ['X' 'X' '^' '<']

 ---------------------
[0 0 0 1] ['>' '>' '>' 'X']
[0 0 0 0] ['>' '^' '^' '^']
[0 0 0 0] ['>' '^' '<' '<']
[0 0 0 0] ['X' 'X' '^' '<']

 ---------------------
